apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reliability-lab
resources:
  - namespace.yaml
  - nats.yaml
  - inventory-svc.yaml
  - payments-svc.yaml
  - orders-svc.yaml
  - orders-svc-rollout.yaml
  - email-worker.yaml
commonLabels:
  part-of: reliability-lab
